### ISSUE TITLE
Implementar Pathfinding y Backtracking

### ISSUE THREAD

**Issue by Yen-US** [yenus210/CEvsEstudiantes#2]
Implementación de un algoritmo de pathfinding A* para que los zombies puedan encontar el camino  a la zona de aprobación 

- [x] Investigar

- [x] Implementar

**Comment by ashleyvasquez** [comment]
- [ ] Investigar Backtracking
- [ ] Investigar Pathfinding A* 
- [ ] Implementar Backtracking
- [ ] Implementar Pathfinding A*
